# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f5896bd36083f42213026b5f12c74867d9c03453259c35fcf6cd379cf8c8d1b4472e9417a92f4fbcb7dfcd939480c19b98fdc61c795388fec1733a7886dc34d

test:
  secret_key_base: 4981601bc858662f32828af292aaaa0888a8f4958dc7129614bda79f73393448852ab392e62c9c586dca0d82becb0723ff87e77abc9a0a3a90a597215c469793

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
